accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/detail/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/commentcreate/', views.commentcreate, name='commentcreate'),
    path('<int:article_pk>/commentdelete/<int:comment_pk>/', views.commentdelete, name='commentdelete'),
    path('<int:article_pk>/liked/', views.liked, name='liked'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')), 
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
# conf
from django.conf import settings 


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    # auto_now_add
    created_at = models.DateTimeField(auto_now_add=True)
    # auto_now
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')

    # () X / 들여쓰기
    class Meta:
        ordering = ('-pk', )


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk', )

accounts/forms.py
# 회원정보 수정 필요없음 
# # UserChangeForm
from django.contrib.auth.forms import UserChangeForm
# get_user_model
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        #
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name', ]

articles/forms.py
#
from django import forms
from .models import Article, Comment


#
class ArticleForm(forms.ModelForm):

    class Meta:
        #
        model = Article
        fields = ['title', 'content', ] 


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        #
        fields = ['content', ]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
# AuthenticationForm 로그인할때 필요 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# login logout 필요
from django.contrib.auth import login as auth_login, logout as auth_logout 
from django.contrib.auth.decorators import login_required 
# 회원정보 수정 없어서 필요없음 
from .forms import CustomUserChangeForm


# create 복사하고할것 
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        # request 
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            #
            auth_login(request, form.get_user())
            # 장고 DB 의 세션과 웹 쿠키가 남아있으면 로그인된 상태로 서버가 켜짐 / 세션을 DB 가 아닌 메모리에 저장한다면 자동 로그아웃 
            # GET 은 query 를 받아오기 위한 함수 / 일반적으로 GET 요청으로 오기 때문에 명시적으로 표시됨 
            # next_page = request.GET.get('next')
            # return redirect(next_page or 'articles:index')
            return redirect('articles:index')
    else:
        #
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def logout(request):
    #
    auth_logout(request)
    return redirect('articles:index')


# require_POST
@require_POST
def delete(request):
    if request.user.is_authenticated:
    # 
        request.user.delete()
    #
    return redirect('articles:index')

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
#
from django.views.decorators.http import require_POST, require_GET
#
from django.contrib.auth.decorators import login_required 
# 
from django.http import HttpResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


@require_GET
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


@login_required
def create(request):
    # if request.user.is_authenticated:
    if request.method == 'POST':
        articleform = ArticleForm(request.POST)
        if articleform.is_valid():
            article = articleform.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index') 
    else: 
        articleform = ArticleForm()
    context = {'articleform': articleform}
    return render(request, 'articles/create.html', context)


@require_GET
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    commentform = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'commentform': commentform,
    }
    return render(request, 'articles/detail.html', context)


@login_required
# create 와 같은 html 로 가도 상관없음 
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 이걸 먼저?
    if article.user == request.user:
        if request.method == 'POST':
            #
            article = ArticleForm(request.POST, instance=article)
            if article.is_valid():
                article.save()
                return redirect('articles:index') 
        else: 
            #
            articleform = ArticleForm(instance=article)
    # 다른 사람 처리 
    else:
        return redirect('articles:detail', article_pk)
    context = {'articleform': articleform}
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, article_pk):
    #
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else: 
            return redirect('articles:detail', article_pk)
    #
    return redirect('articles:index')


@require_POST
def commentcreate(request, article_pk):
    #
    if request.user.is_authenticated:
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            # .save
            comment = commentform.save(commit=False)
            comment.article_id = article_pk
            #
            comment.user = request.user
            comment.save()
            return redirect('articles:detail', article_pk) 


@require_POST
def commentdelete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
        return redirect('articles:detail', article_pk) 
    #
    return HttpResponse('Error', status=401)


# login_required!!!
@login_required
def liked(request, article_pk):
    # request.user
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)
    if user in article.liked_users.all():
        # remove!!
        user.liked_articles.remove(article)
    else:
        user.liked_articles.add(article)
    return redirect('articles:detail', article_pk) 

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Accounts::login{% endblock title %}

{% block container %}
<h2>CREATE</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">login</button>
</form>
{% endblock container %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Accounts::Signup{% endblock title %}

{% block container %}
<h2>CREATE</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">signup</button>
</form>
{% endblock container %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Articles::Create{% endblock title %}

{% block container %}
<h2>CREATE</h2>
<form method="POST">
  {% csrf_token %}
  {{ articleform.as_p }}
  <button type="submit">create</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Articles::DETAIL{% endblock title %}

{% block container %}
<h2>DETAIL</h2>

{{ article.title }}<br>
{{ article.content }}<br>
{{ article.created_at }}<br>
{{ article.updated_at }}<hr>

<form action="{% url 'articles:liked' article.pk %}" method="post">
  {% csrf_token %}
  <button type="submit">좋아요</button>
</form>
<!-- () 빼세요 -->
<!-- <p>{{ article.liked_users.all | length }}명이 좋아합니다.</p> -->
<p>{{ article.liked_users.count }}명이 좋아합니다.</p>

<a href="{% url 'articles:index' %}">index</a>
<!--  -->
{% if request.user == article.user %}
<a href="{% url 'articles:update' article.pk %}">update</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button type="submit">delete</button>
</form>
{% endif %}
<hr>

{% for comment in comments %}
{{ comment.content }}
{% if request.user == comment.user %}
<form action="{% url 'articles:commentdelete' article.pk comment.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">commentdelete</button>
</form>
<br>
{% endif %}
{% endfor %}
<hr>

<form action="{% url 'articles:commentcreate' article.pk %}" method="POST">
  {{ commentform.as_p }}
  {% csrf_token %}
  <button type="submit">commentcreate</button>
</form>

{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Articles::Index{% endblock title %}

{% block container %}
<h2>INDEX</h2>
<!-- username -->
{{ user.username }}
<!-- user.is_authenticated -->
{% if user.is_authenticated %}
  <a href="{% url 'accounts:logout' %}">logout</a>
  <form action="{% url 'accounts:delete' %}" method="post">
    {% csrf_token %}
    <button type="submit">delete</button>
  </form>
  <a href="{% url 'articles:create' %}">create</a>
{% else %}
  <a href="{% url 'accounts:signup' %}">signup</a>
  <a href="{% url 'accounts:login' %}">login</a>
{% endif %}
<hr>
{% for article in articles %}
<a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a><br>
{% endfor %}
{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Articles::Update{% endblock title %}

{% block container %}
<h2>UPDATE</h2>
<form method="POST">
  {% csrf_token %}
  {{ articleform.as_p }}
  <button type="submit">update</button>
</form>
{% endblock container %}

practice/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block container %}
  {% endblock container %}
</body>
</html>